### ISSUE TITLE
HDF5ExtError with table_to_df

### ISSUE THREAD

**Issue by robroc** [ianepreston/stats_can#15]
First time user here.

stats_can==2.2.1
Python 3.6.7
Windows 7

When I ran `table_to_df` on table number "11-10-0055-01" I got the following error:

```HDF5ExtError: HDF5 error back trace

  File "..\src\H5F.c", line 444, in H5Fcreate
    unable to create file
  File "..\src\H5Fint.c", line 1531, in H5F_open
    unable to truncate a file which is already open

End of HDF5 error back trace

Unable to open/create file 'G:\My Drive\Data\Inequality\pytables-hh3a6tzc.tmp'
```

The stats_can.h5 file was created and it's 14.6 MB. The .tmp file was created in the folder, but it's 0 KB.

Full trace:

```
---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
~\AppData\Local\Continuum\miniconda3\envs\data\lib\site-packages\stats_can\sc.py in table_from_h5(table, h5file, path)
    315     try:
--> 316         with pd.HDFStore(h5, "r") as store:
    317             df = pd.read_hdf(store, key=table)

~\AppData\Local\Continuum\miniconda3\envs\data\lib\site-packages\pandas\io\pytables.py in __init__(self, path, mode, complevel, complib, fletcher32, **kwargs)
    504         self._filters = None
--> 505         self.open(mode=mode, **kwargs)
    506 

~\AppData\Local\Continuum\miniconda3\envs\data\lib\site-packages\pandas\io\pytables.py in open(self, mode, **kwargs)
    626         try:
--> 627             self._handle = tables.open_file(self._path, self._mode, **kwargs)
    628         except (IOError) as e:  # pragma: no cover

~\AppData\Local\Continuum\miniconda3\envs\data\lib\site-packages\tables\file.py in open_file(filename, mode, title, root_uep, filters, **kwargs)
    314     # Finally, create the File instance, and return it
--> 315     return File(filename, mode, title, root_uep, filters, **kwargs)
    316 

~\AppData\Local\Continuum\miniconda3\envs\data\lib\site-packages\tables\file.py in __init__(self, filename, mode, title, root_uep, filters, **kwargs)
    777         # Now, it is time to initialize the File extension
--> 778         self._g_new(filename, mode, **params)
    779 

tables/hdf5extension.pyx in tables.hdf5extension.File._g_new()

~\AppData\Local\Continuum\miniconda3\envs\data\lib\site-packages\tables\utils.py in check_file_access(filename, mode)
    153         if not os.access(filename, os.F_OK):
--> 154             raise IOError("``%s`` does not exist" % (filename,))
    155         if not os.path.isfile(filename):

OSError: ``G:\My Drive\Data\Inequality\stats_can.h5`` does not exist

During handling of the above exception, another exception occurred:

HDF5ExtError                              Traceback (most recent call last)
<ipython-input-1-be10fa992c2e> in <module>
      2 sc = StatsCan()
      3 
----> 4 rich = sc.table_to_df("11-10-0055-01")
      5 
      6 rich

~\AppData\Local\Continuum\miniconda3\envs\data\lib\site-packages\stats_can\api_class.py in table_to_df(self, table)
     55         call StatsCan.update_tables(), optionally passing just the table number of interest
     56         """
---> 57         return sc.table_to_df(table=table, path=self.data_folder, h5file="stats_can.h5")
     58 
     59     @staticmethod

~\AppData\Local\Continuum\miniconda3\envs\data\lib\site-packages\stats_can\sc.py in table_to_df(table, path, h5file)
    562     """
    563     if h5file:
--> 564         df = table_from_h5(table=table, h5file=h5file, path=path)
    565     else:
    566         df = zip_table_to_dataframe(table=table, path=path)

~\AppData\Local\Continuum\miniconda3\envs\data\lib\site-packages\stats_can\sc.py in table_from_h5(table, h5file, path)
    318     except (KeyError, OSError):
    319         print("Downloading and loading " + table)
--> 320         tables_to_h5(tables=table, h5file=h5file, path=path)
    321         with pd.HDFStore(h5, "r") as store:
    322             df = pd.read_hdf(store, key=table)

~\AppData\Local\Continuum\miniconda3\envs\data\lib\site-packages\stats_can\sc.py in tables_to_h5(tables, h5file, path)
    281             df_json = json.load(f_name)
    282         with pd.HDFStore(h5file, "a") as store:
--> 283             df.to_hdf(store, key=hkey, format="table", complevel=1)
    284         with h5py.File(h5file, "a") as hfile:
    285             if jkey in hfile.keys():

~\AppData\Local\Continuum\miniconda3\envs\data\lib\site-packages\pandas\core\generic.py in to_hdf(self, path_or_buf, key, **kwargs)
   2528         from pandas.io import pytables
   2529 
-> 2530         pytables.to_hdf(path_or_buf, key, self, **kwargs)
   2531 
   2532     def to_msgpack(self, path_or_buf=None, encoding="utf-8", **kwargs):

~\AppData\Local\Continuum\miniconda3\envs\data\lib\site-packages\pandas\io\pytables.py in to_hdf(path_or_buf, key, value, mode, complevel, complib, append, **kwargs)
    276             path_or_buf, mode=mode, complevel=complevel, complib=complib
    277         ) as store:
--> 278             f(store)
    279     else:
    280         f(path_or_buf)

~\AppData\Local\Continuum\miniconda3\envs\data\lib\site-packages\pandas\io\pytables.py in <lambda>(store)
    269         f = lambda store: store.append(key, value, **kwargs)
    270     else:
--> 271         f = lambda store: store.put(key, value, **kwargs)
    272 
    273     path_or_buf = _stringify_path(path_or_buf)

~\AppData\Local\Continuum\miniconda3\envs\data\lib\site-packages\pandas\io\pytables.py in put(self, key, value, format, append, **kwargs)
    957             format = get_option("io.hdf.default_format") or "fixed"
    958         kwargs = self._validate_format(format, kwargs)
--> 959         self._write_to_group(key, value, append=append, **kwargs)
    960 
    961     def remove(self, key, where=None, start=None, stop=None):

~\AppData\Local\Continuum\miniconda3\envs\data\lib\site-packages\pandas\io\pytables.py in _write_to_group(self, key, value, format, index, append, complib, encoding, **kwargs)
   1526 
   1527         if s.is_table and index:
-> 1528             s.create_index(columns=index)
   1529 
   1530     def _read_group(self, group, **kwargs):

~\AppData\Local\Continuum\miniconda3\envs\data\lib\site-packages\pandas\io\pytables.py in create_index(self, columns, optlevel, kind)
   3648                             "data_columns when initializing the table."
   3649                         )
-> 3650                     v.create_index(**kw)
   3651 
   3652     def read_axes(self, where, **kwargs):

~\AppData\Local\Continuum\miniconda3\envs\data\lib\site-packages\tables\table.py in create_index(self, optlevel, kind, filters, tmp_dir, _blocksizes, _testmode, _verbose)
   3600                              "elements")
   3601         idxrows = _column__create_index(self, optlevel, kind, filters,
-> 3602                                         tmp_dir, _blocksizes, _verbose)
   3603         return SizeType(idxrows)
   3604 

~\AppData\Local\Continuum\miniconda3\envs\data\lib\site-packages\tables\table.py in _column__create_index(self, optlevel, kind, filters, tmp_dir, blocksizes, verbose)
    312         expectedrows=expectedrows,
    313         byteorder=table.byteorder,
--> 314         blocksizes=blocksizes)
    315 
    316     table._set_column_indexing(self.pathname, True)

~\AppData\Local\Continuum\miniconda3\envs\data\lib\site-packages\tables\index.py in __init__(self, parentnode, name, atom, title, kind, optlevel, filters, tmp_dir, expectedrows, byteorder, blocksizes, new)
    393         """The `open_file()` function, to avoid a circular import."""
    394 
--> 395         super(Index, self).__init__(parentnode, name, title, new, filters)
    396 
    397     def _g_post_init_hook(self):

~\AppData\Local\Continuum\miniconda3\envs\data\lib\site-packages\tables\group.py in __init__(self, parentnode, name, title, new, filters, _log)
    233 
    234         # Finally, set up this object as a node.
--> 235         super(Group, self).__init__(parentnode, name, _log)
    236 
    237     def _g_post_init_hook(self):

~\AppData\Local\Continuum\miniconda3\envs\data\lib\site-packages\tables\node.py in __init__(self, parentnode, name, _log)
    271 
    272             # This allows extra operations after creating the node.
--> 273             self._g_post_init_hook()
    274         except:
    275             # If anything happens, the node must be closed

~\AppData\Local\Continuum\miniconda3\envs\data\lib\site-packages\tables\index.py in _g_post_init_hook(self)
    547         # Finally, create a temporary file for indexes if needed
    548         if self.temp_required:
--> 549             self.create_temp()
    550 
    551 

~\AppData\Local\Continuum\miniconda3\envs\data\lib\site-packages\tables\index.py in create_temp(self)
   1010         os.close(fd)
   1011         # Create the proper PyTables file
-> 1012         self.tmpfile = self._openFile(self.tmpfilename, "w")
   1013         self.tmp = tmp = self.tmpfile.root
   1014         cs = self.chunksize

~\AppData\Local\Continuum\miniconda3\envs\data\lib\site-packages\tables\file.py in open_file(filename, mode, title, root_uep, filters, **kwargs)
    313 
    314     # Finally, create the File instance, and return it
--> 315     return File(filename, mode, title, root_uep, filters, **kwargs)
    316 
    317 

~\AppData\Local\Continuum\miniconda3\envs\data\lib\site-packages\tables\file.py in __init__(self, filename, mode, title, root_uep, filters, **kwargs)
    776 
    777         # Now, it is time to initialize the File extension
--> 778         self._g_new(filename, mode, **params)
    779 
    780         # Check filters and set PyTables format version for new files.

tables/hdf5extension.pyx in tables.hdf5extension.File._g_new()

HDF5ExtError: HDF5 error back trace

  File "..\src\H5F.c", line 444, in H5Fcreate
    unable to create file
  File "..\src\H5Fint.c", line 1531, in H5F_open
    unable to truncate a file which is already open

End of HDF5 error back trace

Unable to open/create file 'G:\My Drive\Data\Inequality\pytables-hh3a6tzc.tmp'
```

**Comment by ianepreston** [comment]
@robroc I haven't run into that before, so this is going to take some guessing. It kind of sounds similar to [this stackoverflow](https://stackoverflow.com/questions/49239961/why-is-h5py-h5f-create-failing-with-oserror-unable-to-open-file-name-name) Can you share a snippet of how you're specifying the path to stats_can.h5?

**Comment by robroc** [comment]
The folder path is this:

`sc = StatsCan(data_folder="G:\My Drive\Data\statscanpy_data")`

But I just realized something. My G drive is a Google Drive that I access as any other folder via Google Drive File Stream. Maybe this is permission issue, but it's odd, since files and folders are getting created fine. It's really the .tmp file that seems to be causing a problem.

**Comment by ianepreston** [comment]
Definitely plausible. Can you give it a shot on a local drive and see if you still have the issue?

**Comment by robroc** [comment]
Yeah, that was definitely the issue. It worked just fine on a local drive. Which is a bummer, because I keep all my data in Google Drive for when I work remotely, but that's a problem I have to deal with.

Thanks for the quick attention.

**Comment by ianepreston** [comment]
That's definitely a bummer. If I was going to rebuild this project I probably wouldn't use HDF5 as the backend. I could still see myself redoing it in a future release. 
From the looks of [this](http://matthewrocklin.com/blog/work/2018/02/06/hdf-in-the-cloud) HDF5 is just dodgy on cloud storage.

I guess the workaround would be to have a wrapper at the top of your script to copy the h5 file off G drive to local storage, do your work and then push it back up. Not ideal at all.

I'm going to close this issue and make a (long term) improvement item to change the storage backend.
